services:
  nginx:
    build: requirements/nginx
    networks:
      - Inception
    env_file: .env
    container_name: nginx
    restart: on-failure
    depends_on:
      - wordpress
  wordpress:
    build: requirements/wordpress
    networks:
      - Inception
    env_file: .env
    container_name: wordpress
    ports:
      - "443:443"
    restart: on-failure
    depends_on:
      - mariadb
    volumes:
      - wp_data:/var/www/wordpress
  mariadb:
    build: requirements/mariadb
    networks:
      - Inception
    env_file: .env
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
  
volumes:
  db_data: {}
  wp_data: {}

networks:
  Inception:
    driver: bridge