version: '3'
services:
  mariadb:
    build: ./requirements/mariadb
    env_file: .env
    container_name: mariadb
    restart: always
    volumes:
      - db_data:/var/lib/mysql
  wordpress:
    depends_on:
      - mariadb
    image: wordpress:latest
    env_file: .env
    container_name: wordpress
    ports:
      - "8000:80"
    restart: always
    volumes:
      - ./wordpress_data:/var/www/html
  nginx:
    build: ./requirements/nginx
    env_file: .env
    container_name: nginx
    restart: always

volumes:
  db_data: {}