services:
  nginx:
    build: requirements/nginx
    networks:
      - Inception
    env_file: .env
    container_name: nginx
    restart: on-failure
    depends_on:
      - wordpress
    ports:
      - "443:443"  
  wordpress:
    build: requirements/wordpress
    networks:
      - Inception
    env_file: .env
    container_name: wordpress
    restart: on-failure
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    expose:
      - "9000"
  mariadb:
    build: requirements/mariadb
    networks:
      - Inception
    env_file: .env
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - "3306"

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'C:\Users\Lorick\Documents\42cursus\05-Inception\srcs\wp_data'
  mariadb:
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind'
      device: 'C:\Users\Lorick\Documents\42cursus\05-Inception\srcs\db_data'

networks:
  Inception:
    driver: bridge